# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestAutomationFilterColorIDB04():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testAutomationFilterColorIDB04(self):
    self.driver.get("https://shop.demoqa.com/shop/?filter_color=59")
    self.driver.set_window_size(1936, 1056)
    self.driver.find_element(By.CSS_SELECTOR, ".custom-logo:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".padding-stylebox:nth-child(1) .noo-product-item:nth-child(3) .noo-thumbnail-product:nth-child(1)").click()
    self.driver.find_element(By.ID, "pa_color").click()
    dropdown = self.driver.find_element(By.ID, "pa_color")
    dropdown.find_element(By.XPATH, "//option[. = 'Mauve']").click()
    self.driver.find_element(By.ID, "pa_size").click()
    dropdown = self.driver.find_element(By.ID, "pa_size")
    dropdown.find_element(By.XPATH, "//option[. = 'Medium']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".single_add_to_cart_button").click()
    self.driver.find_element(By.LINK_TEXT, "View cart").click()
    self.driver.find_element(By.CSS_SELECTOR, ".alt").click()
    self.driver.find_element(By.ID, "billing_company").click()
    self.driver.find_element(By.ID, "place_order").click()
    self.driver.find_element(By.ID, "terms").click()
    self.driver.find_element(By.ID, "place_order").click()
    element = self.driver.find_element(By.ID, "place_order")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
  
